### ISSUE TITLE
다른 언어의 주제도 가능한가요?

### ISSUE THREAD

**Issue by Ailrun** [stunstunstun/awesome-wiki#62]

**Comment by stunstunstun** [comment]
네 물론 가능합니다 :)
[Fundamental](https://github.com/stunstunstun/awesome-wiki/tree/master/Fundamental) 카테고리 또는 새로운 언어를 위한 카테고리를 위한 폴더를 생성하시고 문서를 작성해주시면 됩니다 

감사합니다.
