### ISSUE TITLE
소개페이지에 저자의 소개를 추가

### ISSUE THREAD

**Issue by stunstunstun** [stunstunstun/awesome-wiki#64]
[소개 페이지](https://www.holaxprogramming.com/introduce/)에 저자 리스트를 추가할까 합니다. Commiter 분들은 가능하시면 아래의 정보를 코멘트 부탁드립니다.

@Ailrun @holacorp 

`예시)`
- 저자 이름(닉네임) - 정민혁
- 저자 프로필 이미지 - https://www.holaxprogramming.com/image/profile.jpg
- 저자 대표 URL - https://github.com/stunstunstun
- 소개 - 세계 곳곳을 돌아다니면 프로그래밍하기를 바라는 철부지입니다.

**Comment by Ailrun** [comment]
@stunstunstun
- 저자 이름: Clare Jang
- 저자 프로필: https://avatars0.githubusercontent.com/u/12473268?s=600&v=4
- 저자 대표 URL: https//github.com/ailrun
- 소개: Functional Programming 을 향한 산악가

**Comment by stunstunstun** [comment]
@Ailrun 소개페이지가 업데이트 되었습니다.
- https://www.holaxprogramming.com/introduce/

더욱 많은 분들이 참여하였으면 좋겠네요, 이 이슈는 당분간 Close하지 않고 유지합니다.

**Comment by Ailrun** [comment]
@stunstunstun 모바일에서 소개 페이지가 깨지는군요.

**Comment by stunstunstun** [comment]
@Ailrun 마크다운 문서에 억지로 HTML Tag를 넣으니 어려움이 많군요, 수정되었습니다.
