### ISSUE TITLE
문서의 수정

### ISSUE THREAD

**Issue by Ailrun** [stunstunstun/awesome-wiki#65]
문서의 수정은 자유로운가요?
이런 저런 내용에 대한 규약을 담은 문서도 필요해보입니다.
물론 기본적으로는 README.md 가 되겠지요.

**Comment by stunstunstun** [comment]
네, 이미 포스팅된 문서도 지속적으로 업데이트하고 있습니다. README.md에 가이드된 내용 이외에 제약사항을 두지 않았으면 합니다.

변경 내역이 있다면 PR 이슈내에서 리뷰하는 것으로 충분할 것 같아요 :)

**Comment by Ailrun** [comment]
@dotkebi 그럼 그런 내용을 명시해놓는게 좋을 것 같아요.
무언가 제약사항이 있는데 명시되어 있지 않다고 생각할 수 있으니...
아니면 제가 못 본 건가요?

**Comment by stunstunstun** [comment]
@Ailrun 좋은 의견입니다. 아래 PR 확인해주세요.
- https://github.com/stunstunstun/awesome-wiki/pull/66
