### ISSUE TITLE
[요청] RSS 추가 가능할까요? 

### ISSUE THREAD

**Issue by seungdols** [stunstunstun/awesome-wiki#75]
* 좋은 위키 페이지를 알게 되었는데, rss기능이 없어서 좀 아쉬운데 혹시 추가가 가능하실지...
* jekyll기반 테마라면, rss 기능은 제가 직접 추가하고, PR 날려도 괜찮을까요?

**Comment by stunstunstun** [comment]
현재 문서 작성과 배포하는 Repo가 나뉘어져있습니다. 전부는 아니지만 정리가 되어 공개할만한 글들은 아래의 페이지로 배포하고 있습니다.
- https://www.holaxprogramming.com/

RSS 주소는 아래와 같구요.
- https://www.holaxprogramming.com/atom.xml

관심 가져주셔서 감사합니다 :D 관심이 있으시다면 저자로 참여해주세요!
- https://www.holaxprogramming.com/introduce/

**Comment by seungdols** [comment]
@stunstunstun atom이 이미 있군요. 감사합니다! 👍
