### ISSUE TITLE
Git merge와 rebase의 활용

### ISSUE THREAD

**Issue by stunstunstun** [stunstunstun/awesome-wiki#76]
## To Do

- [ ] Why?
- [ ] 내부 동작
- [ ] 실습, Branches
- [ ] 협업시에 협의와 활용

## References

- https://www.kernel.org/pub/software/scm/git/docs/git-rebase.html
- https://www.atlassian.com/git/tutorials/merging-vs-rebasing
- https://git-scm.com/book/ko/v1/Git-%EB%B8%8C%EB%9E%9C%EC%B9%98-Rebase%ED%95%98%EA%B8%B0

**Comment by rocks-leazy** [comment]
Think about approaching history management, Read below link.
https://git-scm.com/book/en/v2/Git-Branching-Rebasing
